import 'dart:math';

class BancoFrases {
  static const _frases = [
    {'id': 1,   'frase': 'Mereces sentirte bien.',                                               'area': 'identidad', 'intensidad': 'suave'},
    {'id': 2,   'frase': 'Eres un museo de todo lo que has amado.',                              'area': 'identidad', 'intensidad': 'media'},
    {'id': 3,   'frase': 'La única forma es a través.',                                          'area': 'cambio',    'intensidad': 'intensa'},
    {'id': 4,   'frase': 'El caos puede ser excelente.',                                         'area': 'cambio',    'intensidad': 'media'},
    {'id': 5,   'frase': 'Ser vulnerable es lo más valiente que puedes hacer.',                  'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 6,   'frase': 'A partir de hoy, cada momento con tus amigos es sagrado.',             'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 7,   'frase': 'Memento mori.',                                                        'area': 'tiempo',    'intensidad': 'intensa'},
    {'id': 8,   'frase': 'Carpe diem.',                                                          'area': 'tiempo',    'intensidad': 'media'},
    {'id': 9,   'frase': 'Déjalo ir.',                                                           'area': 'cambio',    'intensidad': 'intensa'},
    {'id': 10,  'frase': 'No te ahogues en tu propio amor.',                                     'area': 'amor',      'intensidad': 'intensa'},
    {'id': 11,  'frase': 'Confía en que tu corazón te ayudará a encontrar el amor de nuevo.',    'area': 'amor',      'intensidad': 'media'},
    {'id': 12,  'frase': 'No hay un mañana garantizado.',                                        'area': 'tiempo',    'intensidad': 'intensa'},
    {'id': 13,  'frase': 'Alguien piensa seguido en ti.',                                        'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 14,  'frase': 'La belleza en tu corazón te traerá cosas bellas.',                     'area': 'identidad', 'intensidad': 'suave'},
    {'id': 15,  'frase': 'No tienes que estar de acuerdo con todo esto.',                        'area': 'identidad', 'intensidad': 'media'},
    {'id': 16,  'frase': 'Puedes ser fuerte y amable al mismo tiempo.',                          'area': 'identidad', 'intensidad': 'suave'},
    {'id': 17,  'frase': 'El descanso también es productivo.',                                   'area': 'cuerpo',    'intensidad': 'suave'},
    {'id': 18,  'frase': 'No todos los silencios necesitan llenarse.',                           'area': 'soledad',   'intensidad': 'suave'},
    {'id': 19,  'frase': 'Extrañar es una forma de amar.',                                       'area': 'duelo',     'intensidad': 'media'},
    {'id': 20,  'frase': 'Tu ritmo no está roto.',                                               'area': 'identidad', 'intensidad': 'media'},
    {'id': 21,  'frase': 'Hay cosas que solo el tiempo puede decir.',                            'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 22,  'frase': 'No tienes que ganarte tu propio espacio.',                             'area': 'identidad', 'intensidad': 'media'},
    {'id': 23,  'frase': 'El miedo y el deseo suelen ser la misma cosa.',                        'area': 'miedo',     'intensidad': 'intensa'},
    {'id': 24,  'frase': 'Alguien guarda una foto tuya con cariño.',                             'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 25,  'frase': 'No toda herida necesita explicación.',                                  'area': 'duelo',     'intensidad': 'media'},
    {'id': 26,  'frase': 'Puedes empezar de nuevo sin borrarte.',                                'area': 'cambio',    'intensidad': 'media'},
    {'id': 27,  'frase': 'Lo que evitas también te define.',                                     'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 28,  'frase': 'Hay amor que todavía no has conocido.',                                'area': 'amor',      'intensidad': 'suave'},
    {'id': 29,  'frase': 'No todo lo que se fue era tuyo.',                                      'area': 'duelo',     'intensidad': 'intensa'},
    {'id': 30,  'frase': 'Tus contradicciones también son válidas.',                             'area': 'identidad', 'intensidad': 'media'},
    {'id': 31,  'frase': 'El cuerpo sabe antes que la mente.',                                   'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 32,  'frase': 'Mereces cosas que aún no sabes pedir.',                                'area': 'identidad', 'intensidad': 'media'},
    {'id': 33,  'frase': 'Algunos capítulos no tienen cierre y está bien.',                      'area': 'duelo',     'intensidad': 'media'},
    {'id': 34,  'frase': 'No tienes que entenderlo todo para seguir.',                           'area': 'cambio',    'intensidad': 'suave'},
    {'id': 35,  'frase': 'La soledad a veces es un regalo que no pediste.',                      'area': 'soledad',   'intensidad': 'media'},
    {'id': 36,  'frase': 'Estás más cerca de lo que crees.',                                     'area': 'propósito', 'intensidad': 'suave'},
    {'id': 37,  'frase': 'No todo amor que duele está mal.',                                     'area': 'amor',      'intensidad': 'intensa'},
    {'id': 38,  'frase': 'Amar sin perder es el verdadero reto.',                                'area': 'amor',      'intensidad': 'intensa'},
    {'id': 39,  'frase': 'El amor que buscas también te busca.',                                 'area': 'amor',      'intensidad': 'suave'},
    {'id': 40,  'frase': 'No confundas intensidad con profundidad.',                             'area': 'amor',      'intensidad': 'intensa'},
    {'id': 41,  'frase': 'Mereces un amor que no tengas que descifrar.',                         'area': 'amor',      'intensidad': 'media'},
    {'id': 42,  'frase': 'A veces el amor llega disfrazado de calma.',                          'area': 'amor',      'intensidad': 'suave'},
    {'id': 43,  'frase': 'No todo vínculo roto fue un error.',                                   'area': 'vínculos',  'intensidad': 'media'},
    {'id': 44,  'frase': 'Querer a alguien no siempre es suficiente razón.',                    'area': 'amor',      'intensidad': 'intensa'},
    {'id': 45,  'frase': 'El amor propio no es egoísmo, es el inicio.',                         'area': 'identidad', 'intensidad': 'media'},
    {'id': 46,  'frase': 'Hay amores que enseñan más que los que quedan.',                       'area': 'amor',      'intensidad': 'media'},
    {'id': 47,  'frase': 'No busques en otros lo que aún no te has dado.',                      'area': 'amor',      'intensidad': 'intensa'},
    {'id': 48,  'frase': 'Amar bien es también saber despedirse.',                              'area': 'amor',      'intensidad': 'intensa'},
    {'id': 49,  'frase': 'El amor real no pide que te achiques.',                               'area': 'amor',      'intensidad': 'intensa'},
    {'id': 50,  'frase': 'Hay personas que llegan justo a tiempo.',                             'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 51,  'frase': 'No todo silencio entre dos es distancia.',                            'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 52,  'frase': 'Puedes amar y aun así poner límites.',                               'area': 'amor',      'intensidad': 'media'},
    {'id': 53,  'frase': 'El amor que te asusta puede ser el más honesto.',                     'area': 'amor',      'intensidad': 'intensa'},
    {'id': 54,  'frase': 'No tienes que entender por qué alguien te quiere.',                   'area': 'amor',      'intensidad': 'media'},
    {'id': 55,  'frase': 'Algunas personas son hogar aunque no se queden.',                     'area': 'vínculos',  'intensidad': 'media'},
    {'id': 56,  'frase': 'El desamor también es una forma de crecer.',                          'area': 'duelo',     'intensidad': 'media'},
    {'id': 57,  'frase': 'El esfuerzo silencioso también cuenta.',                              'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 58,  'frase': 'No toda ambición necesita justificarse.',                             'area': 'trabajo',   'intensidad': 'media'},
    {'id': 59,  'frase': 'Descansar no es rendirse.',                                           'area': 'trabajo',   'intensidad': 'media'},
    {'id': 60,  'frase': 'Lo que construyes hoy importa aunque no lo veas.',                    'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 61,  'frase': 'No tienes que amar lo que haces para hacerlo bien.',                  'area': 'trabajo',   'intensidad': 'media'},
    {'id': 62,  'frase': 'El éxito tiene muchas definiciones, elige la tuya.',                  'area': 'trabajo',   'intensidad': 'media'},
    {'id': 63,  'frase': 'No toda oportunidad perdida era la correcta.',                        'area': 'trabajo',   'intensidad': 'media'},
    {'id': 64,  'frase': 'Crear algo desde cero es un acto de valentía.',                       'area': 'trabajo',   'intensidad': 'media'},
    {'id': 65,  'frase': 'No te compares con quien lleva más tiempo.',                          'area': 'trabajo',   'intensidad': 'media'},
    {'id': 66,  'frase': 'El trabajo que nadie ve también tiene valor.',                        'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 67,  'frase': 'Pedir ayuda no es señal de incompetencia.',                           'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 68,  'frase': 'Tu mejor idea aún no ha llegado.',                                    'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 69,  'frase': 'No tienes que saberlo todo para empezar.',                            'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 70,  'frase': 'La constancia supera al talento casi siempre.',                       'area': 'trabajo',   'intensidad': 'media'},
    {'id': 71,  'frase': 'No toda pausa es un retroceso.',                                      'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 72,  'frase': 'Hay dignidad en cualquier trabajo bien hecho.',                       'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 73,  'frase': 'El camino lento también llega.',                                      'area': 'trabajo',   'intensidad': 'suave'},
    {'id': 74,  'frase': 'No dejes que el miedo al fracaso dicte tu agenda.',                   'area': 'trabajo',   'intensidad': 'intensa'},
    {'id': 75,  'frase': 'Hacer poco con intención vale más que mucho sin dirección.',          'area': 'trabajo',   'intensidad': 'media'},
    {'id': 76,  'frase': 'Tu trabajo refleja quién eres, no todo lo que vales.',               'area': 'trabajo',   'intensidad': 'media'},
    {'id': 77,  'frase': 'Tu cuerpo te ha traído hasta aquí.',                                  'area': 'cuerpo',    'intensidad': 'suave'},
    {'id': 78,  'frase': 'El cansancio también es información.',                                'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 79,  'frase': 'No tienes que ganarte el derecho a descansar.',                       'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 80,  'frase': 'Escucha lo que tu cuerpo dice antes de que grite.',                   'area': 'cuerpo',    'intensidad': 'intensa'},
    {'id': 81,  'frase': 'Moverse es una forma de procesar lo que la mente no puede.',         'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 82,  'frase': 'No le debes a nadie una versión diferente de tu cuerpo.',            'area': 'cuerpo',    'intensidad': 'intensa'},
    {'id': 83,  'frase': 'El placer también es necesario.',                                     'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 84,  'frase': 'Dormir bien es un acto revolucionario.',                              'area': 'cuerpo',    'intensidad': 'suave'},
    {'id': 85,  'frase': 'Tu cuerpo no es un proyecto, es tu casa.',                           'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 86,  'frase': 'No toda incomodidad física es insignificante.',                       'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 87,  'frase': 'Respirar profundo es el reset más accesible que tienes.',             'area': 'cuerpo',    'intensidad': 'suave'},
    {'id': 88,  'frase': 'Comer con calma es un acto de amor propio.',                         'area': 'cuerpo',    'intensidad': 'suave'},
    {'id': 89,  'frase': 'El cuerpo guarda lo que la mente niega.',                             'area': 'cuerpo',    'intensidad': 'intensa'},
    {'id': 90,  'frase': 'No tienes que sentirte bien todo el tiempo para estar bien.',         'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 91,  'frase': 'Hay sabiduría en lo que tu cuerpo rechaza.',                         'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 92,  'frase': 'Mover el cuerpo cambia el estado de la mente.',                      'area': 'cuerpo',    'intensidad': 'suave'},
    {'id': 93,  'frase': 'No te castigues con el cuerpo por lo que pasa en la mente.',         'area': 'cuerpo',    'intensidad': 'intensa'},
    {'id': 94,  'frase': 'Tu energía es finita, úsala con criterio.',                          'area': 'cuerpo',    'intensidad': 'media'},
    {'id': 95,  'frase': 'El cuerpo sana a su propio ritmo.',                                   'area': 'cuerpo',    'intensidad': 'suave'},
    {'id': 96,  'frase': 'No necesitas una razón especial para cuidarte.',                      'area': 'cuerpo',    'intensidad': 'suave'},
    {'id': 97,  'frase': 'La abundancia empieza por creer que la mereces.',                     'area': 'dinero',    'intensidad': 'media'},
    {'id': 98,  'frase': 'No todo lo que cuesta dinero vale la pena.',                         'area': 'dinero',    'intensidad': 'media'},
    {'id': 99,  'frase': 'Gastar en ti no siempre es un lujo.',                                'area': 'dinero',    'intensidad': 'suave'},
    {'id': 100, 'frase': 'El dinero es una herramienta, no una medida de valor.',              'area': 'dinero',    'intensidad': 'media'},
    {'id': 101, 'frase': 'No tienes que tenerlo todo resuelto para empezar a ahorrar.',        'area': 'dinero',    'intensidad': 'suave'},
    {'id': 102, 'frase': 'La generosidad no requiere tener de sobra.',                         'area': 'dinero',    'intensidad': 'suave'},
    {'id': 103, 'frase': 'No toda deuda es un fracaso.',                                       'area': 'dinero',    'intensidad': 'media'},
    {'id': 104, 'frase': 'Lo que produces tiene más valor del que crees.',                     'area': 'dinero',    'intensidad': 'media'},
    {'id': 105, 'frase': 'Poner precio a tu trabajo es un acto de respeto propio.',            'area': 'dinero',    'intensidad': 'media'},
    {'id': 106, 'frase': 'No tienes que disculparte por querer más.',                          'area': 'dinero',    'intensidad': 'media'},
    {'id': 107, 'frase': 'La escasez a veces es una creencia, no una realidad.',               'area': 'dinero',    'intensidad': 'intensa'},
    {'id': 108, 'frase': 'Invertir en ti siempre es buen negocio.',                            'area': 'dinero',    'intensidad': 'suave'},
    {'id': 109, 'frase': 'No toda seguridad económica viene de afuera.',                       'area': 'dinero',    'intensidad': 'media'},
    {'id': 110, 'frase': 'El dinero que pides prestado también pesa emocionalmente.',          'area': 'dinero',    'intensidad': 'intensa'},
    {'id': 111, 'frase': 'Hay riqueza que no se mide en cuentas bancarias.',                   'area': 'dinero',    'intensidad': 'suave'},
    {'id': 112, 'frase': 'No confundas precio con valor.',                                     'area': 'dinero',    'intensidad': 'media'},
    {'id': 113, 'frase': 'Dar con miedo no es generosidad.',                                   'area': 'dinero',    'intensidad': 'intensa'},
    {'id': 114, 'frase': 'Lo que tienes hoy fue suficiente para llegar hasta aquí.',           'area': 'dinero',    'intensidad': 'suave'},
    {'id': 115, 'frase': 'No tienes que avergonzarte de necesitar más.',                       'area': 'dinero',    'intensidad': 'media'},
    {'id': 116, 'frase': 'La prosperidad también puede llegar de formas inesperadas.',         'area': 'dinero',    'intensidad': 'suave'},
    {'id': 117, 'frase': 'No tienes que ser consistente para ser auténtico.',                  'area': 'identidad', 'intensidad': 'media'},
    {'id': 118, 'frase': 'Cambiar de opinión es señal de inteligencia.',                       'area': 'identidad', 'intensidad': 'media'},
    {'id': 119, 'frase': 'No toda versión de ti tiene que gustarle a todos.',                  'area': 'identidad', 'intensidad': 'media'},
    {'id': 120, 'frase': 'Eres más que el rol que desempeñas.',                                'area': 'identidad', 'intensidad': 'media'},
    {'id': 121, 'frase': 'No tienes que explicar quién eres.',                                 'area': 'identidad', 'intensidad': 'media'},
    {'id': 122, 'frase': 'Tu historia no te define, pero sí te forma.',                        'area': 'identidad', 'intensidad': 'media'},
    {'id': 123, 'frase': 'Puedes reinventarte sin traicionarte.',                              'area': 'identidad', 'intensidad': 'media'},
    {'id': 124, 'frase': 'No toda etiqueta que te pusieron es verdad.',                        'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 125, 'frase': 'Conocerte es el trabajo de toda una vida.',                          'area': 'identidad', 'intensidad': 'suave'},
    {'id': 126, 'frase': 'No tienes que elegir entre versiones de ti.',                        'area': 'identidad', 'intensidad': 'media'},
    {'id': 127, 'frase': 'Tus rarezas son parte de tu firma.',                                 'area': 'identidad', 'intensidad': 'suave'},
    {'id': 128, 'frase': 'No dejes que el miedo al juicio dicte quién eres.',                  'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 129, 'frase': 'Eres una persona en proceso, no un producto terminado.',             'area': 'identidad', 'intensidad': 'media'},
    {'id': 130, 'frase': 'No tienes que encajar en ningún molde para pertenecer.',             'area': 'identidad', 'intensidad': 'media'},
    {'id': 131, 'frase': 'Lo que te avergüenza a veces es lo más tuyo que tienes.',            'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 132, 'frase': 'Puedes ser muchas cosas al mismo tiempo.',                           'area': 'identidad', 'intensidad': 'suave'},
    {'id': 133, 'frase': 'No toda crisis de identidad es una pérdida.',                        'area': 'identidad', 'intensidad': 'media'},
    {'id': 134, 'frase': 'El yo que fuiste también merece compasión.',                         'area': 'identidad', 'intensidad': 'media'},
    {'id': 135, 'frase': 'No tienes que tener clara tu identidad para vivir con intención.',   'area': 'identidad', 'intensidad': 'suave'},
    {'id': 136, 'frase': 'Eres suficiente exactamente como eres hoy.',                         'area': 'identidad', 'intensidad': 'suave'},
    {'id': 137, 'frase': 'No todo final es una pérdida.',                                      'area': 'cambio',    'intensidad': 'media'},
    {'id': 138, 'frase': 'El cambio que temes ya está en camino.',                             'area': 'cambio',    'intensidad': 'intensa'},
    {'id': 139, 'frase': 'No tienes que estar listo para empezar.',                            'area': 'cambio',    'intensidad': 'media'},
    {'id': 140, 'frase': 'Soltar es a veces el acto más valiente.',                            'area': 'cambio',    'intensidad': 'intensa'},
    {'id': 141, 'frase': 'No toda transformación es visible desde afuera.',                    'area': 'cambio',    'intensidad': 'suave'},
    {'id': 142, 'frase': 'El caos es a veces el primer paso del orden.',                       'area': 'cambio',    'intensidad': 'media'},
    {'id': 143, 'frase': 'No tienes que entender el cambio para navegarlo.',                   'area': 'cambio',    'intensidad': 'media'},
    {'id': 144, 'frase': 'Algunas puertas se cierran para que otras puedan abrirse.',         'area': 'cambio',    'intensidad': 'suave'},
    {'id': 145, 'frase': 'No todo lo que termina debería continuar.',                          'area': 'cambio',    'intensidad': 'intensa'},
    {'id': 146, 'frase': 'El miedo al cambio y el deseo de cambio coexisten.',                'area': 'cambio',    'intensidad': 'media'},
    {'id': 147, 'frase': 'No tienes que despedirte de todo lo anterior para avanzar.',        'area': 'cambio',    'intensidad': 'media'},
    {'id': 148, 'frase': 'Los cambios lentos también son cambios.',                            'area': 'cambio',    'intensidad': 'suave'},
    {'id': 149, 'frase': 'No toda ruptura es un fracaso.',                                     'area': 'cambio',    'intensidad': 'media'},
    {'id': 150, 'frase': 'Hay versiones de ti esperando del otro lado.',                       'area': 'cambio',    'intensidad': 'media'},
    {'id': 151, 'frase': 'No tienes que saber a dónde vas para dar el siguiente paso.',       'area': 'cambio',    'intensidad': 'suave'},
    {'id': 152, 'frase': 'El antes y el después no siempre tienen una línea clara.',           'area': 'cambio',    'intensidad': 'media'},
    {'id': 153, 'frase': 'No todo cambio necesita un anuncio.',                               'area': 'cambio',    'intensidad': 'suave'},
    {'id': 154, 'frase': 'Resistir el cambio también es información sobre lo que valoras.',   'area': 'cambio',    'intensidad': 'media'},
    {'id': 155, 'frase': 'No tienes que celebrar cada transformación para que sea válida.',   'area': 'cambio',    'intensidad': 'suave'},
    {'id': 156, 'frase': 'Lo que cambia en ti a veces cambia todo lo demás.',                 'area': 'cambio',    'intensidad': 'intensa'},
    {'id': 157, 'frase': 'No todos los vínculos están hechos para durar.',                    'area': 'vínculos',  'intensidad': 'intensa'},
    {'id': 158, 'frase': 'Las amistades también necesitan cuidado.',                           'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 159, 'frase': 'No tienes que caerle bien a todos.',                                'area': 'vínculos',  'intensidad': 'media'},
    {'id': 160, 'frase': 'Hay personas que llegaron a enseñarte algo específico.',             'area': 'vínculos',  'intensidad': 'media'},
    {'id': 161, 'frase': 'No toda distancia es abandono.',                                    'area': 'vínculos',  'intensidad': 'media'},
    {'id': 162, 'frase': 'Los vínculos sanos no agotan.',                                     'area': 'vínculos',  'intensidad': 'media'},
    {'id': 163, 'frase': 'No tienes que mantener relaciones que ya cumplieron su ciclo.',     'area': 'vínculos',  'intensidad': 'intensa'},
    {'id': 164, 'frase': 'Pedir perdón a tiempo es un regalo para ambos.',                    'area': 'vínculos',  'intensidad': 'media'},
    {'id': 165, 'frase': 'No toda pelea es el fin de algo.',                                  'area': 'vínculos',  'intensidad': 'media'},
    {'id': 166, 'frase': 'Hay personas que te quieren más de lo que crees.',                  'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 167, 'frase': 'No tienes que merecer el amor de quienes te quieren.',              'area': 'vínculos',  'intensidad': 'media'},
    {'id': 168, 'frase': 'Los lazos invisibles también sostienen.',                            'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 169, 'frase': 'No toda amistad necesita verse seguido para ser real.',             'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 170, 'frase': 'Recibir también es un acto de generosidad.',                        'area': 'vínculos',  'intensidad': 'media'},
    {'id': 171, 'frase': 'No tienes que ser el mismo con todos para ser auténtico.',          'area': 'vínculos',  'intensidad': 'media'},
    {'id': 172, 'frase': 'Hay vínculos que sanan sin que te des cuenta.',                     'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 173, 'frase': 'No toda cercanía es intimidad.',                                    'area': 'vínculos',  'intensidad': 'intensa'},
    {'id': 174, 'frase': 'Las personas que te desafían también te quieren.',                  'area': 'vínculos',  'intensidad': 'media'},
    {'id': 175, 'frase': 'No tienes que estar disponible para todos todo el tiempo.',         'area': 'vínculos',  'intensidad': 'media'},
    {'id': 176, 'frase': 'El vínculo más importante que tienes es contigo mismo.',            'area': 'vínculos',  'intensidad': 'media'},
    {'id': 177, 'frase': 'No tienes que apurarte para llegar a ningún lado.',                 'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 178, 'frase': 'El presente es el único lugar donde puedes actuar.',               'area': 'tiempo',    'intensidad': 'media'},
    {'id': 179, 'frase': 'No toda espera es tiempo perdido.',                                 'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 180, 'frase': 'Lo que hiciste ayer importa menos que lo que haces hoy.',          'area': 'tiempo',    'intensidad': 'media'},
    {'id': 181, 'frase': 'No tienes que haber llegado ya.',                                   'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 182, 'frase': 'El pasado no tiene voto en tu presente.',                           'area': 'tiempo',    'intensidad': 'intensa'},
    {'id': 183, 'frase': 'No toda nostalgia es señal de que algo estuvo mejor.',              'area': 'tiempo',    'intensidad': 'media'},
    {'id': 184, 'frase': 'El futuro que imaginas no es el único posible.',                    'area': 'tiempo',    'intensidad': 'media'},
    {'id': 185, 'frase': 'No tienes que resolver hoy lo que es de mañana.',                  'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 186, 'frase': 'Hay momentos que solo se entienden después.',                       'area': 'tiempo',    'intensidad': 'media'},
    {'id': 187, 'frase': 'No toda lentitud es retraso.',                                      'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 188, 'frase': 'El tiempo que dedicas a descansar también cuenta.',                 'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 189, 'frase': 'No tienes que correr al ritmo de los demás.',                       'area': 'tiempo',    'intensidad': 'media'},
    {'id': 190, 'frase': 'Los momentos ordinarios también merecen atención.',                 'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 191, 'frase': 'No todo lo urgente es importante.',                                  'area': 'tiempo',    'intensidad': 'media'},
    {'id': 192, 'frase': 'El tiempo que pasó también te construyó.',                          'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 193, 'frase': 'No tienes que saber cuánto falta para seguir caminando.',           'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 194, 'frase': 'Hay cosas que solo llegan cuando dejas de buscarlas.',              'area': 'tiempo',    'intensidad': 'media'},
    {'id': 195, 'frase': 'No toda demora es un no.',                                          'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 196, 'frase': 'Vivir despacio también es una forma de vivir bien.',               'area': 'tiempo',    'intensidad': 'suave'},
    {'id': 197, 'frase': 'El miedo y el coraje no son opuestos.',                             'area': 'miedo',     'intensidad': 'media'},
    {'id': 198, 'frase': 'No tienes que eliminar el miedo para actuar.',                      'area': 'miedo',     'intensidad': 'media'},
    {'id': 199, 'frase': 'Lo que te paraliza también te está diciendo algo.',                 'area': 'miedo',     'intensidad': 'intensa'},
    {'id': 200, 'frase': 'No todo riesgo termina en catástrofe.',                             'area': 'miedo',     'intensidad': 'media'},
    {'id': 201, 'frase': 'El peor escenario que imaginas rara vez ocurre exactamente así.',  'area': 'miedo',     'intensidad': 'media'},
    {'id': 202, 'frase': 'No tienes que ser valiente todo el tiempo.',                        'area': 'miedo',     'intensidad': 'suave'},
    {'id': 203, 'frase': 'El miedo a veces protege, otras veces solo limita.',               'area': 'miedo',     'intensidad': 'media'},
    {'id': 204, 'frase': 'No toda incomodidad es una señal de peligro.',                     'area': 'miedo',     'intensidad': 'media'},
    {'id': 205, 'frase': 'Hacer algo con miedo también cuenta como valentía.',               'area': 'miedo',     'intensidad': 'media'},
    {'id': 206, 'frase': 'No tienes que entender de dónde viene el miedo para moverte.',    'area': 'miedo',     'intensidad': 'media'},
    {'id': 207, 'frase': 'Lo que evitas cobra más poder cada vez.',                          'area': 'miedo',     'intensidad': 'intensa'},
    {'id': 208, 'frase': 'No toda ansiedad sobre el futuro es profecía.',                    'area': 'miedo',     'intensidad': 'media'},
    {'id': 209, 'frase': 'El miedo al rechazo es casi universal, no solo tuyo.',             'area': 'miedo',     'intensidad': 'suave'},
    {'id': 210, 'frase': 'No tienes que convencer a nadie de que tu miedo es válido.',       'area': 'miedo',     'intensidad': 'media'},
    {'id': 211, 'frase': 'Nombrar el miedo lo hace más pequeño.',                            'area': 'miedo',     'intensidad': 'media'},
    {'id': 212, 'frase': 'No toda precaución es cobardía.',                                  'area': 'miedo',     'intensidad': 'suave'},
    {'id': 213, 'frase': 'El miedo a equivocarte ya no puede ser tu guía.',                  'area': 'miedo',     'intensidad': 'intensa'},
    {'id': 214, 'frase': 'No tienes que sentirte listo para dar el paso.',                   'area': 'miedo',     'intensidad': 'media'},
    {'id': 215, 'frase': 'Hay miedos que heredaste y que no son tuyos.',                     'area': 'miedo',     'intensidad': 'intensa'},
    {'id': 216, 'frase': 'Lo que te da miedo a veces es exactamente lo que necesitas.',      'area': 'miedo',     'intensidad': 'intensa'},
    {'id': 217, 'frase': 'El duelo no tiene una forma correcta.',                            'area': 'duelo',     'intensidad': 'suave'},
    {'id': 218, 'frase': 'No tienes que superar las cosas en el tiempo que otros esperan.',  'area': 'duelo',     'intensidad': 'media'},
    {'id': 219, 'frase': 'Llorar también es avanzar.',                                       'area': 'duelo',     'intensidad': 'media'},
    {'id': 220, 'frase': 'No toda tristeza necesita una razón clara.',                       'area': 'duelo',     'intensidad': 'media'},
    {'id': 221, 'frase': 'El dolor que sientes es proporcional a lo que amaste.',            'area': 'duelo',     'intensidad': 'intensa'},
    {'id': 222, 'frase': 'No tienes que estar bien para seguir adelante.',                   'area': 'duelo',     'intensidad': 'media'},
    {'id': 223, 'frase': 'Extrañar algo que ya no existe no es debilidad.',                  'area': 'duelo',     'intensidad': 'media'},
    {'id': 224, 'frase': 'No toda pérdida se anuncia.',                                      'area': 'duelo',     'intensidad': 'intensa'},
    {'id': 225, 'frase': 'Hay duelos que no tienen nombre pero igual pesan.',                'area': 'duelo',     'intensidad': 'intensa'},
    {'id': 226, 'frase': 'No tienes que olvidar para sanar.',                                'area': 'duelo',     'intensidad': 'media'},
    {'id': 227, 'frase': 'El tiempo no borra, transforma.',                                  'area': 'duelo',     'intensidad': 'media'},
    {'id': 228, 'frase': 'No toda cicatriz es una herida sin resolver.',                     'area': 'duelo',     'intensidad': 'media'},
    {'id': 229, 'frase': 'Puedes cargar algo con tristeza y seguir viviendo.',               'area': 'duelo',     'intensidad': 'media'},
    {'id': 230, 'frase': 'No tienes que estar listo para soltar cuando otros lo esperan.',   'area': 'duelo',     'intensidad': 'intensa'},
    {'id': 231, 'frase': 'Hay partes de ti que también mueren cuando pierdes a alguien.',    'area': 'duelo',     'intensidad': 'intensa'},
    {'id': 232, 'frase': 'No todo duelo es por una persona.',                                'area': 'duelo',     'intensidad': 'media'},
    {'id': 233, 'frase': 'Sanar no significa que no duela a veces.',                         'area': 'duelo',     'intensidad': 'media'},
    {'id': 234, 'frase': 'No tienes que agradecer el dolor para crecer con él.',             'area': 'duelo',     'intensidad': 'intensa'},
    {'id': 235, 'frase': 'El duelo y la alegría pueden coexistir.',                          'area': 'duelo',     'intensidad': 'media'},
    {'id': 236, 'frase': 'No tienes que estar roto para estar de duelo.',                    'area': 'duelo',     'intensidad': 'media'},
    {'id': 237, 'frase': 'La soledad elegida es un lujo.',                                   'area': 'soledad',   'intensidad': 'suave'},
    {'id': 238, 'frase': 'No toda soledad es ausencia de amor.',                             'area': 'soledad',   'intensidad': 'suave'},
    {'id': 239, 'frase': 'Estar solo no es lo mismo que estar abandonado.',                  'area': 'soledad',   'intensidad': 'media'},
    {'id': 240, 'frase': 'No tienes que llenar cada silencio.',                              'area': 'soledad',   'intensidad': 'suave'},
    {'id': 241, 'frase': 'La soledad puede ser el espacio donde te encuentras.',             'area': 'soledad',   'intensidad': 'media'},
    {'id': 242, 'frase': 'No toda compañía alivia la soledad.',                              'area': 'soledad',   'intensidad': 'intensa'},
    {'id': 243, 'frase': 'Hay momentos en que solo tú puedes acompañarte.',                  'area': 'soledad',   'intensidad': 'media'},
    {'id': 244, 'frase': 'No tienes que huir de estar contigo mismo.',                       'area': 'soledad',   'intensidad': 'intensa'},
    {'id': 245, 'frase': 'La soledad incómoda también tiene algo que enseñarte.',            'area': 'soledad',   'intensidad': 'intensa'},
    {'id': 246, 'frase': 'No toda soledad es permanente.',                                   'area': 'soledad',   'intensidad': 'suave'},
    {'id': 247, 'frase': 'Hay una diferencia entre estar solo y sentirse solo.',             'area': 'soledad',   'intensidad': 'media'},
    {'id': 248, 'frase': 'No tienes que entretenerte para sobrevivir la soledad.',           'area': 'soledad',   'intensidad': 'media'},
    {'id': 249, 'frase': 'Aprender a estar solo es aprender a estar contigo.',              'area': 'soledad',   'intensidad': 'media'},
    {'id': 250, 'frase': 'No toda soledad es señal de que algo está mal.',                  'area': 'soledad',   'intensidad': 'suave'},
    {'id': 251, 'frase': 'Hay sabiduría que solo llega en silencio.',                        'area': 'soledad',   'intensidad': 'media'},
    {'id': 252, 'frase': 'No tienes que tener compañía para sentirte completo.',             'area': 'soledad',   'intensidad': 'media'},
    {'id': 253, 'frase': 'La soledad a veces es donde nace lo mejor de ti.',                'area': 'soledad',   'intensidad': 'media'},
    {'id': 254, 'frase': 'No toda noche solitaria es una noche triste.',                    'area': 'soledad',   'intensidad': 'suave'},
    {'id': 255, 'frase': 'Estar contigo mismo sin huir es una habilidad que se aprende.',   'area': 'soledad',   'intensidad': 'media'},
    {'id': 256, 'frase': 'No tienes que justificar tu necesidad de soledad.',               'area': 'soledad',   'intensidad': 'suave'},
    {'id': 257, 'frase': 'Lo ordinario también merece atención.',                            'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 258, 'frase': 'No tienes que esperar las cosas grandes para sentir gratitud.',   'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 259, 'frase': 'Hay belleza en lo que ya tienes y aún no ves.',                   'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 260, 'frase': 'No toda gratitud necesita expresarse en voz alta.',               'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 261, 'frase': 'Lo que das por hecho alguna vez fue lo que más pediste.',         'area': 'gratitud',  'intensidad': 'intensa'},
    {'id': 262, 'frase': 'No tienes que fingir gratitud cuando no la sientes.',             'area': 'gratitud',  'intensidad': 'media'},
    {'id': 263, 'frase': 'Hay personas en tu vida que merecen más reconocimiento.',         'area': 'gratitud',  'intensidad': 'media'},
    {'id': 264, 'frase': 'No toda bendición llega envuelta para regalo.',                   'area': 'gratitud',  'intensidad': 'media'},
    {'id': 265, 'frase': 'El cuerpo que tienes hoy ha hecho cosas extraordinarias.',        'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 266, 'frase': 'No tienes que estar en tu mejor momento para reconocer lo bueno.','area': 'gratitud',  'intensidad': 'suave'},
    {'id': 267, 'frase': 'Hay pequeñas cosas que sostienen tu día sin que lo notes.',       'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 268, 'frase': 'No toda gratitud es por lo que salió bien.',                      'area': 'gratitud',  'intensidad': 'media'},
    {'id': 269, 'frase': 'A veces agradecer empieza por no quejarse un momento.',           'area': 'gratitud',  'intensidad': 'media'},
    {'id': 270, 'frase': 'No tienes que tenerlo todo para sentir que tienes suficiente.',   'area': 'gratitud',  'intensidad': 'media'},
    {'id': 271, 'frase': 'Hay amor a tu alrededor que no siempre ves.',                     'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 272, 'frase': 'No toda gratitud resuelve el dolor, pero sí lo acompaña.',        'area': 'gratitud',  'intensidad': 'media'},
    {'id': 273, 'frase': 'Lo que tienes hoy fue el sueño de alguien más.',                  'area': 'gratitud',  'intensidad': 'intensa'},
    {'id': 274, 'frase': 'No tienes que ser optimista para practicar la gratitud.',         'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 275, 'frase': 'Hay momentos del pasado que merecen un gracias tardío.',          'area': 'gratitud',  'intensidad': 'media'},
    {'id': 276, 'frase': 'No toda gratitud es hacia afuera, también puede ser hacia ti.',   'area': 'gratitud',  'intensidad': 'suave'},
    {'id': 277, 'frase': 'No tienes que tener una misión clara para vivir con sentido.',    'area': 'propósito', 'intensidad': 'suave'},
    {'id': 278, 'frase': 'El propósito se encuentra haciendo, no pensando.',               'area': 'propósito', 'intensidad': 'media'},
    {'id': 279, 'frase': 'No toda vocación llega como revelación.',                         'area': 'propósito', 'intensidad': 'media'},
    {'id': 280, 'frase': 'Lo que te mueve no siempre tiene nombre.',                        'area': 'propósito', 'intensidad': 'media'},
    {'id': 281, 'frase': 'No tienes que cambiar el mundo para que tu vida importe.',        'area': 'propósito', 'intensidad': 'suave'},
    {'id': 282, 'frase': 'Hay propósito en los actos pequeños y constantes.',              'area': 'propósito', 'intensidad': 'suave'},
    {'id': 283, 'frase': 'No toda pasión tiene que convertirse en trabajo.',                'area': 'propósito', 'intensidad': 'media'},
    {'id': 284, 'frase': 'Lo que haces con amor deja huella aunque no lo veas.',           'area': 'propósito', 'intensidad': 'suave'},
    {'id': 285, 'frase': 'No tienes que saber tu para qué para empezar a vivir.',          'area': 'propósito', 'intensidad': 'suave'},
    {'id': 286, 'frase': 'El sentido a veces se construye en retrospectiva.',               'area': 'propósito', 'intensidad': 'media'},
    {'id': 287, 'frase': 'No toda crisis de propósito es el fin de algo.',                  'area': 'propósito', 'intensidad': 'media'},
    {'id': 288, 'frase': 'Hay dignidad en cualquier camino elegido con intención.',         'area': 'propósito', 'intensidad': 'suave'},
    {'id': 289, 'frase': 'No tienes que inspirar a otros para que tu vida tenga valor.',   'area': 'propósito', 'intensidad': 'media'},
    {'id': 290, 'frase': 'Lo que te da energía también te indica hacia dónde ir.',         'area': 'propósito', 'intensidad': 'media'},
    {'id': 291, 'frase': 'No todo propósito es grandioso, algunos son íntimos y suficientes.','area': 'propósito','intensidad': 'suave'},
    {'id': 292, 'frase': 'Hay momentos en que sobrevivir ya es suficiente propósito.',     'area': 'propósito', 'intensidad': 'intensa'},
    {'id': 293, 'frase': 'No tienes que justificar lo que le da sentido a tu vida.',       'area': 'propósito', 'intensidad': 'media'},
    {'id': 294, 'frase': 'El propósito cambia con el tiempo y eso está bien.',             'area': 'propósito', 'intensidad': 'suave'},
    {'id': 295, 'frase': 'No toda dirección tiene que ser para siempre.',                  'area': 'propósito', 'intensidad': 'suave'},
    {'id': 296, 'frase': 'Lo que construyes hoy, aunque no lo veas, ya importa.',          'area': 'propósito', 'intensidad': 'suave'},
    {'id': 297, 'frase': 'No tienes que tener todo claro para saber que vas bien.',        'area': 'propósito', 'intensidad': 'suave'},
    {'id': 298, 'frase': 'El camino que eliges también te elige a ti.',                    'area': 'propósito', 'intensidad': 'media'},
    {'id': 299, 'frase': 'No toda vida extraordinaria se ve extraordinaria desde adentro.','area': 'propósito', 'intensidad': 'intensa'},
    {'id': 300, 'frase': 'Estás exactamente donde necesitas estar hoy.',                   'area': 'propósito', 'intensidad': 'suave'},
    {'id': 301, 'frase': 'No puedes usar el mapa de alguien más para encontrarte.',        'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 302, 'frase': 'No te disculpes por existir.',                                   'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 303, 'frase': 'Necesitas estar con alguien que te permita mostrarte como eres.','area': 'amor',      'intensidad': 'media'},
    {'id': 304, 'frase': 'Quien sea que experimente tu amor lo recordará toda la vida.',   'area': 'amor',      'intensidad': 'suave'},
    {'id': 305, 'frase': 'Eres muy popular.',                                              'area': 'vínculos',  'intensidad': 'suave'},
    {'id': 306, 'frase': 'No eres tan especial.',                                          'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 307, 'frase': 'A veces te quedas por costumbre, no por amor.',                  'area': 'amor',      'intensidad': 'intensa'},
    {'id': 308, 'frase': 'No necesitas convencer a nadie de elegirte.',                    'area': 'amor',      'intensidad': 'intensa'},
    {'id': 309, 'frase': 'A veces te falta decir lo que ya sabes.',                        'area': 'identidad', 'intensidad': 'media'},
    {'id': 310, 'frase': 'No confundas atención con interés.',                             'area': 'amor',      'intensidad': 'intensa'},
    {'id': 311, 'frase': 'No todo lo intenso es real.',                                    'area': 'amor',      'intensidad': 'intensa'},
    {'id': 312, 'frase': 'A veces el problema no eras tú, era el lugar.',                  'area': 'cambio',    'intensidad': 'media'},
    {'id': 313, 'frase': 'No necesitas una razón para irte.',                              'area': 'cambio',    'intensidad': 'intensa'},
    {'id': 314, 'frase': 'Hay personas que te buscan cuando les conviene.',                'area': 'vínculos',  'intensidad': 'intensa'},
    {'id': 315, 'frase': 'Puedes soltar sin dejar de querer.',                             'area': 'duelo',     'intensidad': 'media'},
    {'id': 316, 'frase': 'No todo rechazo habla de tu valor.',                             'area': 'identidad', 'intensidad': 'intensa'},
    {'id': 317, 'frase': 'Hay historias que solo existen para enseñarte algo.',            'area': 'duelo',     'intensidad': 'media'},
    {'id': 318, 'frase': 'No todos los finales son pérdidas.',                             'area': 'duelo',     'intensidad': 'media'},
    {'id': 319, 'frase': 'A veces quedarte es lo que más te cuesta.',                      'area': 'cambio',    'intensidad': 'intensa'},
    {'id': 320, 'frase': 'No todo lo que extrañas te hace bien.',                          'area': 'duelo',     'intensidad': 'intensa'},
    {'id': 321, 'frase': 'Puedes empezar de nuevo sin explicarte.',                        'area': 'cambio',    'intensidad': 'media'},
  ];


  /// Devuelve todos los IDs del banco mezclados al azar.
  /// Se llama cuando la cola del usuario está vacía.
  static List<int> generarColaMezclada() {
    final ids = _frases.map((f) => f['id'] as int).toList();
    ids.shuffle(Random());
    return ids;
  }

  /// Devuelve la frase con el ID dado, priorizando las del signo solar.
  /// Si el ID no coincide con las preferencias del signo, igual la devuelve.
  static Map<String, dynamic> porId(int id) {
    return _frases.firstWhere(
      (f) => f['id'] == id,
      orElse: () => _frases.first,
    );
  }
}
