class BancoFrasesAmigos {
  static const _frases = [
    "[USUARIO] y [AMIGO] se quieren, pero nunca al mismo tiempo.",
    "[AMIGO] ya sabe lo que quiere, solo finge que no.",
    "[USUARIO] siempre llega tarde a sus propias conclusiones.",
    "[USUARIO] y [AMIGO] se entienden mejor cuando no hablan de lo importante.",
    "[AMIGO] necesita que le digan lo que ya sabe.",
    "[USUARIO] empuja, [AMIGO] frena. Ninguno entiende por qué eso funciona.",
    "[AMIGO] está esperando que [USUARIO] lo note primero.",
    "[USUARIO] y [AMIGO] comparten la misma urgencia pero no el mismo destino.",
    "Lo que [USUARIO] llama caos, [AMIGO] lo llama plan.",
    "[AMIGO] admira en [USUARIO] lo que nunca se permitiría a sí mismo.",
    "[USUARIO] confunde intensidad con claridad.",
    "[AMIGO] no cambia de opinión, cambia de máscara.",
    "Ninguno de los dos sabe irse a tiempo.",
    "[USUARIO] escucha para responder. [AMIGO] escucha para defenderse.",
    "[AMIGO] convierte toda duda en distancia.",
    "[USUARIO] actúa como si no necesitara a nadie. Nadie le cree.",
    "A veces [AMIGO] extraña versiones de personas que nunca existieron.",
    "[USUARIO] no quiere control. Quiere garantías.",
    "[AMIGO] deja puertas abiertas solo para comprobar quién vuelve.",
    "Entre [USUARIO] y [AMIGO], alguien siempre está interpretando algo de más.",
    "[USUARIO] convierte silencios pequeños en catástrofes completas.",
    "[AMIGO] aprendió a parecer tranquilo antes de aprender a estarlo.",
    "[USUARIO] y [AMIGO] son compatibles en teoría.",
    "[AMIGO] evita decir la verdad cuando la verdad tiene consecuencias.",
    "[USUARIO] necesita respuestas que nadie puede darle honestamente.",
    "La versión de [AMIGO] que recuerda [USUARIO] ya no existe.",
    "[USUARIO] tiene miedo de aburrirse más que de equivocarse.",
    "[AMIGO] sabe exactamente cuándo volverse imposible de leer.",
    "[USUARIO] no está buscando amor. Está buscando confirmación.",
    "[AMIGO] convierte toda conversación en una prueba invisible.",
    "[USUARIO] quiere cercanía, pero solo bajo sus propias reglas.",
    "[AMIGO] lleva semanas pensando en algo que jamás va a decir.",
    "Ninguno de los dos confía en las cosas fáciles.",
    "[USUARIO] romantiza personas que no sabrían cuidarlo.",
    "[AMIGO] cree que entenderse demasiado arruina la magia.",
    "[USUARIO] y [AMIGO] hablan el mismo idioma emocional con distinto acento.",
    "[AMIGO] no responde porque todavía no decide quién quiere ser.",
    "[USUARIO] se siente más cómodo persiguiendo que teniendo.",
    "La honestidad entre [USUARIO] y [AMIGO] siempre llega tarde.",
    "[AMIGO] quiere ser entendido sin tener que explicarse.",
    "[USUARIO] sospecha de todo lo que llega sin esfuerzo.",
    "[AMIGO] actúa indiferente cuando algo realmente le importa.",
    "[USUARIO] y [AMIGO] tienen el mismo problema con nombres distintos.",
    "[AMIGO] necesita distancia para reconocer lo que siente.",
    "[USUARIO] convierte expectativas pequeñas en historias enormes.",
    "Ambos creen que están siendo más claros de lo que realmente son.",
    "[AMIGO] nunca dice 'quédate', pero tampoco deja ir.",
    "[USUARIO] teme que lo conozcan demasiado y no lo suficiente.",
    "Hay conversaciones entre [USUARIO] y [AMIGO] que solo existen en sus cabezas.",
    "[AMIGO] sigue esperando una versión más sencilla de [USUARIO].",
    "[USUARIO] y [AMIGO] se encuentran justo donde ambos pensaban que nadie los entendería.",
    "[AMIGO] habla poco de lo que siente porque sabe cuánto pesa.",
    "[USUARIO] tiene la extraña costumbre de volver a lugares que ya le dolieron.",
    "Hay algo en [AMIGO] que hace que [USUARIO] baje la guardia sin darse cuenta.",
    "[USUARIO] y [AMIGO] no se prometen nada, pero siempre regresan.",
    "[AMIGO] mira a [USUARIO] como quien reconoce una canción antigua.",
    "[USUARIO] nunca aprendió a querer a medias.",
    "[AMIGO] es más honesto en sus silencios que en muchas conversaciones.",
    "[USUARIO] y [AMIGO] se cuidan de formas que nadie nota.",
    "[AMIGO] sabe quedarse incluso cuando parece distante.",
    "[USUARIO] convierte momentos pequeños en recuerdos permanentes.",
    "[AMIGO] nunca dice todo lo que piensa cuando mira a [USUARIO].",
    "Entre [USUARIO] y [AMIGO], las pausas también significan algo.",
    "[USUARIO] quiere que lo elijan sin tener que pedirlo.",
    "[AMIGO] guarda afecto como quien protege algo frágil.",
    "[USUARIO] y [AMIGO] coinciden más en lo que callan.",
    "[AMIGO] aparenta calma incluso cuando todo le importa demasiado.",
    "[USUARIO] encuentra belleza en personas difíciles de alcanzar.",
    "[AMIGO] quisiera explicar lo que siente sin arruinarlo al decirlo.",
    "[USUARIO] y [AMIGO] se reconocieron antes de entenderse.",
    "[AMIGO] escucha a [USUARIO] como si intentara recordar algo importante.",
    "[USUARIO] tiene el tipo de corazón que siempre vuelve encendido.",
    "[AMIGO] teme perder lo que todavía no sabe cómo cuidar.",
    "[USUARIO] y [AMIGO] se extrañan incluso cuando están cerca.",
    "[AMIGO] deja pequeñas señales esperando que [USUARIO] las note.",
    "[USUARIO] todavía cree en conexiones que no se pueden explicar.",
    "[AMIGO] observa más de lo que admite.",
    "[USUARIO] y [AMIGO] se suavizan mutuamente sin querer.",
    "[AMIGO] nunca aprendió a irse del todo.",
    "[USUARIO] siente demasiado por personas que sienten en silencio.",
    "[AMIGO] tiene una ternura que solo aparece cuando baja la defensa.",
    "[USUARIO] y [AMIGO] podrían arruinarlo todo por miedo a hacerlo real.",
    "[AMIGO] guarda recuerdos como si fueran instrucciones para volver.",
    "[USUARIO] siempre termina encontrando significado donde otros solo ven coincidencias.",
    "[AMIGO] quisiera parecer menos afectado de lo que realmente está.",
    "[USUARIO] y [AMIGO] tienen la clase de conexión que cambia el ritmo de un día.",
    "[AMIGO] piensa en [USUARIO] en momentos absurdamente específicos.",
    "[USUARIO] nunca logra olvidar del todo a quien lo hizo sentirse visto.",
    "[AMIGO] convierte nostalgia en rutina.",
    "[USUARIO] y [AMIGO] son el tipo de historia que nunca empieza del todo ni termina bien.",
    "[AMIGO] siente más de lo que su orgullo le permite decir.",
    "[USUARIO] quisiera que ciertas personas supieran cuánto las eligió.",
    "[AMIGO] siempre regresa emocionalmente antes que físicamente.",
    "[USUARIO] y [AMIGO] se entienden mejor cuando dejan de intentar explicarse.",
    "[AMIGO] tiene miedo de necesitar tanto a alguien.",
    "[USUARIO] lleva tiempo buscando algo que se parezca a sentirse en casa.",
    "[AMIGO] admira la forma en que [USUARIO] sigue sintiendo sin endurecerse.",
    "[USUARIO] y [AMIGO] saben exactamente cómo afectarse mutuamente.",
    "[AMIGO] nunca olvida cómo lo hizo sentir [USUARIO] la primera vez.",
    "[USUARIO] y [AMIGO] siguen orbitándose incluso cuando intentan no hacerlo.",
    "[AMIGO] dice 'ya voy' como concepto filosófico.",
    "[USUARIO] convierte un mensaje visto en una investigación completa.",
    "[AMIGO] está emocionalmente disponible de lunes a miércoles.",
    "[AMIGO] necesita cinco días para procesar una conversación de ocho minutos.",
    "[AMIGO] no está confundido. Solo le gusta el espectáculo.",
    "[USUARIO] y [AMIGO] tienen el timing de dos personas tratando de entrar por la misma puerta.",
    "[AMIGO] convierte cualquier interacción en una prueba psicológica.",
    "[AMIGO] desaparece dos días y regresa con un meme.",
    "[AMIGO] tiene demasiados sentimientos para alguien que responde 'jajaja'.",
    "[USUARIO] ya ensayó esta conversación diecisiete veces.",
    "[AMIGO] aparece justo cuando [USUARIO] piensa en él.",
    "[USUARIO] y [AMIGO] siguen la misma conversación desde hace meses.",
    "[AMIGO] sonríe distinto cerca de [USUARIO].",
    "[USUARIO] guarda mensajes de [AMIGO].",
    "[AMIGO] hace sentir acompañado a [USUARIO] incluso en silencio.",
    "[USUARIO] y [AMIGO] se ríen de cosas incomprensibles.",
    "[AMIGO] siempre sabe qué enviarle a [USUARIO].",
    "[USUARIO] nota todo lo que [AMIGO] intenta ocultar.",
    "[AMIGO] y [USUARIO] ya tienen demasiados chistes internos.",
    "[USUARIO] nunca se siente fuera de lugar con [AMIGO].",
    "[AMIGO] responde más rápido a [USUARIO].",
    "[USUARIO] y [AMIGO] mejoran días normales.",
    "[AMIGO] mira a [USUARIO] con demasiada ternura.",
    "[USUARIO] reconoce el humor de [AMIGO] en un 'hola'.",
    "[AMIGO] comparte primero sus cosas favoritas con [USUARIO].",
    "[USUARIO] y [AMIGO] tienen calma rara juntos.",
    "[AMIGO] recuerda detalles mínimos de [USUARIO].",
    "[USUARIO] sonríe diferente cuando habla de [AMIGO].",
    "[AMIGO] no planeaba encariñarse tanto.",
    "[USUARIO] y [AMIGO] hacen especiales los días simples.",
    "[AMIGO] encuentra adorable a [USUARIO] por razones absurdas.",
    "[USUARIO] ya sabe cuándo [AMIGO] quiere hacerlo reír.",
    "[AMIGO] manda cosas solo porque le recuerdan a [USUARIO].",
    "[USUARIO] y [AMIGO] acortan trayectos largos.",
    "[AMIGO] se siente más ligero después de hablar con [USUARIO].",
    "[USUARIO] ya asocia canciones con [AMIGO].",
    "[AMIGO] nunca dice 'te extrañé', pero aparece más.",
    "[USUARIO] y [AMIGO] ya no saben fingir indiferencia.",
    "[AMIGO] sonríe demasiado viendo mensajes de [USUARIO].",
    "[USUARIO] baja el volumen del mundo con [AMIGO].",
    "[AMIGO] tiene conversaciones favoritas con [USUARIO].",
    "[USUARIO] y [AMIGO] nunca se quedan sin tema.",
    "[AMIGO] ya sabe cómo alegrar a [USUARIO].",
    "[USUARIO] guarda recuerdos de [AMIGO] sin querer.",
    "[AMIGO] siente paz viendo el nombre de [USUARIO].",
    "[USUARIO] y [AMIGO] tienen química haciendo nada.",
    "[AMIGO] escucha distinto cuando habla [USUARIO].",
    "[USUARIO] ya puede imaginar la risa de [AMIGO].",
    "[AMIGO] inicia conversaciones solo para sentir cerca a [USUARIO].",
    "[USUARIO] y [AMIGO] convierten tonterías en recuerdos.",
    "[AMIGO] puede ser más él mismo con [USUARIO].",
    "[USUARIO] siempre termina contándole todo a [AMIGO].",
    "[AMIGO] ya domina el arte de molestar adorablemente a [USUARIO].",
    "[USUARIO] y [AMIGO] mejoran semanas enteras.",
    "[AMIGO] piensa demasiado en conversaciones con [USUARIO].",
    "[USUARIO] nota cosas tiernas de [AMIGO] que nadie más ve.",
    "[AMIGO] nunca esperó sentirse tan entendido.",
    "[USUARIO] y [AMIGO] tienen sincronías extrañas.",
    "[AMIGO] guarda cosas que le recuerdan a [USUARIO].",
    "[USUARIO] siente familiaridad incluso en días raros.",
    "[AMIGO] se ríe más fuerte cerca de [USUARIO].",
    "[USUARIO] y [AMIGO] hacen rápido el tiempo.",
    "[AMIGO] escribe a [USUARIO] aunque no tenga nada que decir.",
    "[USUARIO] reconoce el ánimo de [AMIGO] por cómo escribe.",
    "[AMIGO] se vuelve más suave cerca de [USUARIO].",
    "[USUARIO] y [AMIGO] podrían hablar horas.",
    "[AMIGO] ama hacer reír a [USUARIO].",
    "[USUARIO] siempre encuentra excusas para volver.",
    "[AMIGO] nunca siente incómodos los silencios con [USUARIO].",
    "[USUARIO] y [AMIGO] viven diciendo 'te iba a mandar eso'.",
    "[AMIGO] ya hizo rutina pensar en [USUARIO].",
    "[USUARIO] sonríe viendo notificaciones de [AMIGO].",
    "[AMIGO] siente menos peso hablando con [USUARIO].",
    "[USUARIO] y [AMIGO] se entienden diciendo tonterías.",
    "[AMIGO] recuerda frases pequeñas de [USUARIO].",
    "[USUARIO] puede ser raro tranquilamente con [AMIGO].",
    "[AMIGO] empieza a notar cosas bonitas para contárselas a [USUARIO].",
    "[USUARIO] y [AMIGO] se alegran el día fácilmente.",
    "[AMIGO] todavía sonríe recordando a [USUARIO].",
    "[USUARIO] y [AMIGO] hacen fácil sentirse cerca.",
  ];

  static String seleccionar(String uid1, String uid2, DateTime fecha) {
    final seed = uid1.codeUnits.fold<int>(0, (a, b) => a + b)
        + uid2.codeUnits.fold<int>(0, (a, b) => a + b)
        + fecha.year * 10000 + fecha.month * 100 + fecha.day;
    return _frases[seed % _frases.length];
  }
}
